export const USA = [
  { value: 'MSFT' },   { value: 'AAPL' },   { value: 'GOOGL' },
  { value: 'GOOG' },   { value: 'AMZN' },   { value: 'NVDA' },
  { value: 'META' },   { value: 'BRK-B' },  { value: 'BRK-A' },
  { value: 'LLY' },    { value: 'TSLA' },   { value: 'TSM' },
  { value: 'JPM' },    { value: 'AVGO' },   { value: 'V' },
  { value: 'NVO' },    { value: 'NONOF' },  { value: 'UNH' },
  { value: 'WMT' },    { value: 'LVMUY' },  { value: 'LVMHF' },
  { value: 'XOM' },    { value: 'MA' },     { value: 'JNJ' },
  { value: 'PG' },     { value: 'LTMAY' },  { value: 'HD' },
  { value: 'ASML' },   { value: 'ASMLF' },  { value: 'BAC' },
  { value: 'JPM-PD' }, { value: 'JPM-PC' }, { value: 'TCEHY' },
  { value: 'TCTZF' },  { value: 'ORCL' },   { value: 'BAC-PK' },
  { value: 'COST' },   { value: 'MRK' },    { value: 'NSRGY' },
  { value: 'NSRGF' },  { value: 'BML-PG' }, { value: 'GDVTZ' },
  { value: 'BAC-PL' }, { value: 'BAC-PE' }, { value: 'BML-PH' },
  { value: 'BML-PL' }, { value: 'ABBV' },   { value: 'ADBE' },
  { value: 'CVX' },    { value: 'CRM' },    { value: 'AMD' },
  { value: 'TM' },     { value: 'TOYOF' },  { value: 'LRLCF' },
  { value: 'LRLCY' },  { value: 'KO' },     { value: 'BML-PJ' },
  { value: 'BAC-PB' }, { value: 'NFLX' },   { value: 'FMX' },
  { value: 'IDCBF' },  { value: 'FMXUF' },  { value: 'IDCBY' },
  { value: 'RHHVF' },  { value: 'RHHBF' },  { value: 'PEP' },
  { value: 'ACN' },    { value: 'RHHBY' },  { value: 'HESAY' },
  { value: 'HESAF' },  { value: 'NVS' },    { value: 'NVSEF' },
  { value: 'TMO' },    { value: 'PCCYF' },  { value: 'MCD' },
  { value: 'CSCO' },   { value: 'AZN' },    { value: 'SAPGF' },
  { value: 'SHEL' },   { value: 'SAP' },    { value: 'AZNCF' },
  { value: 'WFC-PY' }, { value: 'LIN' },    { value: 'ABT' },
  { value: 'RYDAF' },  { value: 'TMUS' },   { value: 'CMCSA' },
  { value: 'WFC-PL' }, { value: 'BABAF' },  { value: 'WFC-PR' },
  { value: 'WFC' },    { value: 'ACGBY' },  { value: 'INTC' },
  { value: 'INTU' },   { value: 'DHR' },    { value: 'BABA' },
  { value: 'VZ' },     { value: 'DIS' },    { value: 'IBM' },
  { value: 'AMGN' }
];